env:
  global:
    - secure: DE9IUM+pIV757GU0ccfDJhA752442pKu3DyBthrzHW9+GbsqbfuJOx045CYNN5vOWutFPC0A51B9WxhLNpXXqD3mfU8MhP1gkF7SskrHvcAPrCyfdqZf1Q8XDP5phm2KbHhhwxQMYmmicd6yj8DPNy2wRoSgPSDp/ZUDk51XZDU=
    - DISPLAY=:99.0
  matrix:
    - URHO3D_LIB_TYPE=STATIC ENABLE_64BIT=1
    - URHO3D_LIB_TYPE=SHARED ENABLE_64BIT=1
    - URHO3D_LIB_TYPE=STATIC ENABLE_64BIT=0
    - URHO3D_LIB_TYPE=SHARED ENABLE_64BIT=0
    - URHO3D_LIB_TYPE=STATIC ENABLE_64BIT=0 ANDROID_NDK=1
    - URHO3D_LIB_TYPE=SHARED ENABLE_64BIT=0 ANDROID_NDK=1
#matrix:
#  allow_failures:
#    - env: URHO3D_LIB_TYPE=STATIC ENABLE_64BIT=0
#    - env: URHO3D_LIB_TYPE=SHARED ENABLE_64BIT=0
#    - env: URHO3D_LIB_TYPE=STATIC ENABLE_64BIT=0 ANDROID_NDK=1
#    - env: URHO3D_LIB_TYPE=SHARED ENABLE_64BIT=0 ANDROID_NDK=1
language: cpp
compiler: gcc
before_install:
    - bash -c "[ $ANDROID_NDK ]" && wget -q http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2 && tar xjf *.bz2 && rm *.bz2 && ln -s android-ndk* android-ndk && export ANDROID_NDK=$(pwd)/android-ndk || true
    - bash -c "[ $SITE_UPDATE ] && [ $TRAVIS_PULL_REQUEST == 'false' ]" && sudo add-apt-repository ppa:george-edison55/precise-backports -y || true
    - sudo apt-get update -q -y
install:
    - sudo apt-get install -q -y --no-install-recommends libasound2-dev
    - rvm gemset use global && gem install rake
    - bash -c "[ x$ENABLE_64BIT == 'x0' ]" && sudo apt-get remove -q -y gvfs-daemons && sudo apt-get install -q -y libxrandr-dev:i386 libgl1-mesa-dev:i386 libxext-dev:i386 libxrender-dev:i386 g++-multilib && export CMAKE_PREFIX_PATH=/usr/lib/i386-linux-gnu || true
    - bash -c "[ $SITE_UPDATE ] && [ $TRAVIS_PULL_REQUEST == 'false' ]" && sudo apt-get install -q -y --no-install-recommends doxygen graphviz || true
    - bash -e /etc/init.d/xvfb start
script: rake travis_ci
after_success: rake travis_ci_site_update
